/** DefaultCoa.gs — COA bawaan (dari file "Daftar format upload jurnal transaksi dan default COA"). */
// [kode, nama, normal, pos, kelompok, ndeDefault]
var DEFAULT_COA = [
  ["1001","Kas Kecil IDR","DR","Y","KAS",""],
  ["1002","Kas Operasional IDR","DR","Y","KAS",""],
  ["1003","Kas IDR (Direksi)","DR","Y","KAS",""],
  ["1004","Bank Syariah Indonesia","DR","Y","BANK",""],
  ["1005","Bank Central Asia","DR","Y","BANK",""],
  ["1006","Bank Mandiri","DR","Y","BANK",""],
  ["1007","Bank Rakyat Indonesia","DR","Y","BANK",""],
  ["1008","Bank BNI","DR","Y","BANK",""],
  ["1009","Bank Citibank","DR","Y","BANK",""],
  ["1020","Deposito","DR","Y","SETARA_KAS",""],
  ["1030","Kas dibayar Dimuka","DR","Y","KAS",""],
  ["1040","Kas Uang Makan","DR","Y","KAS",""],
  ["1099","Ayat Silang Cash/Bank","DR","Y","KAS",""],
  ["1101","Piutang Usaha - IDR","DR","Y","PIUTANG_USAHA",""],
  ["1102","Piutang Usaha - USD","DR","Y","PIUTANG_USAHA",""],
  ["1103","Piutang Karyawan","DR","Y","PIUTANG_LAIN",""],
  ["1104","Piutang Direksi","DR","Y","PIUTANG_LAIN",""],
  ["1105","Piutang Lain-Lain","DR","Y","PIUTANG_LAIN",""],
  ["1119","Penyisihan Piutang Usaha","DR","Y","PENYISIHAN_PIUTANG",""],
  ["1129","Penyisihan Piutang Non Usaha","DR","Y","PENYISIHAN_PIUTANG",""],
  ["1201","Persediaan Tools","DR","Y","PERSEDIAAN",""],
  ["1202","Persediaan Material","DR","Y","PERSEDIAAN",""],
  ["1299","Persediaan Lain-Lain","DR","Y","PERSEDIAAN",""],
  ["1301","Uang Muka Pembelian - IDR","DR","Y","UANG_MUKA",""],
  ["1302","Uang Muka Pembelian - USD","DR","Y","UANG_MUKA",""],
  ["1401","Biaya Sewa Dibayar Dimuka","DR","Y","DIBAYAR_DIMUKA",""],
  ["1402","BPJS Dibayar Dimuka","DR","Y","DIBAYAR_DIMUKA",""],
  ["1499","Biaya Dibayar Dimuka Lain-Lain","DR","N","DIBAYAR_DIMUKA",""],
  ["1501","PPN Masukan","DR","Y","PPN_MASUKAN",""],
  ["1502","PPH 23 disetor","DR","Y","PAJAK_DIBAYAR_DIMUKA",""],
  ["1503","PPh 25/29 disetor","DR","N","PAJAK_DIBAYAR_DIMUKA",""],
  ["1504","Uang Muka PPH 22","DR","Y","PAJAK_DIBAYAR_DIMUKA",""],
  ["1561","Investasi Jangka Pendek","DR","Y","INVESTASI_PENDEK",""],
  ["1562","Investasi Jangka Panjang","DR","Y","INVESTASI_PANJANG",""],
  ["1601","Tanah","DR","Y","ASET_TETAP",""],
  ["1602","Bangunan/Gedung","DR","Y","ASET_TETAP",""],
  ["1603","Kendaraan","DR","N","ASET_TETAP",""],
  ["1604","Mesin","DR","Y","ASET_TETAP",""],
  ["1605","Peralatan Kantor/Workshop","DR","Y","ASET_TETAP",""],
  ["1606","Furniture dan Perlengkapan","DR","N","ASET_TETAP",""],
  ["1607","Akumulasi Penyusutan Bangunan/Gedung","CR","Y","AKUM_PENYUSUTAN",""],
  ["1608","Akumulasi Penyusutan Kendaraan","CR","Y","AKUM_PENYUSUTAN",""],
  ["1609","Akumulasi Penyusutan Mesin","CR","Y","AKUM_PENYUSUTAN",""],
  ["1610","Akumulasi Penyusutan Peralatan Kantor","CR","Y","AKUM_PENYUSUTAN",""],
  ["1611","Akumulasi Penyusutan Furniture dan Perlengkapan","CR","Y","AKUM_PENYUSUTAN",""],
  ["1701","Biaya Pendirian","DR","Y","ASET_LAIN",""],
  ["1702","Biaya Pra Operasional","DR","Y","ASET_LAIN",""],
  ["1703","Program","DR","N","ASET_LAIN",""],
  ["1704","Bank Guarantee/Perf. Bond","DR","N","ASET_LAIN",""],
  ["1705","Amortisasi Aktiva Tidak Berwujud","CR","Y","AKUM_AMORTISASI",""],
  ["1709","Aktiva Lain-lain","DR","N","ASET_LAIN",""],
  ["2000","Overdraft","CR","N","UTANG_BANK_PENDEK",""],
  ["2001","Hutang Usaha - IDR","CR","N","UTANG_USAHA",""],
  ["2001.1","Hutang Usaha - CCTV","CR","N","UTANG_USAHA",""],
  ["2001.2","Hutang Usaha - Event","CR","N","UTANG_USAHA",""],
  ["2001.3","Hutang Usaha - Barang","CR","N","UTANG_USAHA",""],
  ["2001.4","Hutang Usaha - Maintenance Lift","CR","N","UTANG_USAHA",""],
  ["2001.5","Hutang Usaha - Seragam","CR","N","UTANG_USAHA",""],
  ["2001.6","Hutang Usaha - Chemical","CR","N","UTANG_USAHA",""],
  ["2001.7","Hutang Usaha - TKJP","CR","N","UTANG_USAHA",""],
  ["2001.8","Hutang Usaha - Packaging","CR","N","UTANG_USAHA",""],
  ["2002","Hutang Usaha - USD","CR","N","UTANG_USAHA",""],
  ["2003","Hutang Aktiva","CR","N","UTANG_LAIN",""],
  ["2004","Hutang Pajak","CR","Y","UTANG_PAJAK",""],
  ["2004-1","PPN Keluaran","CR","Y","UTANG_PAJAK",""],
  ["2004-2","Hutang PPH 21","CR","N","UTANG_PAJAK",""],
  ["2004-3","Hutang PPH 23","CR","N","UTANG_PAJAK",""],
  ["2004-4","Hutang PPH Pasal 4 Ayat 2","CR","Y","UTANG_PAJAK",""],
  ["2004.5","Penyisihan Pajak Penghasilan (PPH Pasal 25/29)","CR","Y","UTANG_PAJAK",""],
  ["2006","Hutang Bank - Jatuh Tempo Dlm 1 tahun","CR","Y","UTANG_BANK_PENDEK",""],
  ["2060","Biaya Yang Masih Harus Dibayar","CR","Y","BIAYA_YMH",""],
  ["2070","Uang Muka Pelanggan","CR","Y","UANG_MUKA_PELANGGAN",""],
  ["2099","Hutang Lain-Lain","CR","Y","UTANG_LAIN",""],
  ["2101","Hutang Leasing","CR","Y","UTANG_LEASING_PENDEK",""],
  ["2102","Hutang Modal Usaha","CR","Y","UTANG_LAIN",""],
  ["2104","Hutang BPJS (JKK,JKM,JHT,JP,Kesehatan)","CR","N","UTANG_LAIN",""],
  ["2201","Hutang Pemegang Saham","CR","N","UTANG_PEMEGANG_SAHAM",""],
  ["2203","Hutang Bank  - Jk Panjang","CR","Y","UTANG_BANK_PANJANG",""],
  ["2205","Hutang Leasing - Jk Panjang","CR","Y","UTANG_LEASING_PANJANG",""],
  ["2209","Hutang Jgk Panjang - lainnya","CR","Y","UTANG_PANJANG_LAIN",""],
  ["3001","Modal Disetor","CR","Y","MODAL",""],
  ["3001.1","Dana Talangan","CR","Y","MODAL",""],
  ["3002","Laba/Rugi Ditahan","CR","N","SALDO_LABA",""],
  ["3003","Laba Bersih","CR","Y","LABA_BERJALAN",""],
  ["3004","Dana Cadangan Pusat","CR","Y","CADANGAN",""],
  ["3100","Dividen","CR","Y","DIVIDEN",""],
  ["4001","Pendapatan Usaha - IDR","CR","N","PENDAPATAN",""],
  ["4002","Pendapatan Usaha - USD","CR","Y","PENDAPATAN",""],
  ["4003","Pendapatan Usaha Lain-Lain","CR","Y","PENDAPATAN",""],
  ["5001","Harga Pokok Pendapatan","DR","Y","HPP",""],
  ["5002","Biaya Pembelian Material Pendukung","DR","Y","HPP",""],
  ["5003","Potongan Pembelian","CR","Y","HPP",""],
  ["5004","Retur Pembelian","CR","N","HPP",""],
  ["5005","Biaya Operasi Lainnya","DR","Y","HPP",""],
  ["5006","Biaya Gaji TKJP","DR","Y","HPP",""],
  ["5007","Biaya THR TKJP","DR","Y","HPP",""],
  ["6001","Biaya Pemasaran","DR","Y","BEBAN_PENJUALAN",""],
  ["6002","Biaya Promosi/Iklan","DR","Y","BEBAN_PENJUALAN",""],
  ["6003","Biaya Komisi Sales","DR","Y","BEBAN_PENJUALAN",""],
  ["6004","Biaya Komisi Pelanggan","DR","Y","BEBAN_PENJUALAN",""],
  ["6099","Biaya Penjualan Lainnya","DR","Y","BEBAN_PENJUALAN",""],
  ["7001","Biaya Gaji Office","DR","Y","BEBAN_UMUM",""],
  ["7002","Biaya THR Office","DR","Y","BEBAN_UMUM",""],
  ["7003","Biaya Bingkisan Office","DR","Y","BEBAN_UMUM",""],
  ["7004","Biaya Konsumsi","DR","N","BEBAN_UMUM",""],
  ["7005","Biaya BPJS (JKK,JKM,JHT,JP,Kesehatan)","DR","Y","BEBAN_UMUM",""],
  ["7006","Biaya Asuransi Mesin","DR","Y","BEBAN_UMUM",""],
  ["7007","Biaya Asuransi Gedung/Inventory","DR","Y","BEBAN_UMUM",""],
  ["7008","Biaya Asuransi Kendaraan","DR","Y","BEBAN_UMUM",""],
  ["7009","Biaya Asuransi Karyawan","DR","Y","BEBAN_UMUM",""],
  ["7010","Biaya Sewa Gedung","DR","N","BEBAN_UMUM",""],
  ["7011","Biaya Sewa Kendaraan","DR","N","BEBAN_UMUM",""],
  ["7012","Biaya Sewa Peralatan Kantor","DR","Y","BEBAN_UMUM",""],
  ["7013","Biaya Perlengkapan Kantor","DR","Y","BEBAN_UMUM",""],
  ["7014","Biaya Perlengkapan Dapur","DR","N","BEBAN_UMUM",""],
  ["7015","Biaya Perlengkapan Workshop","DR","Y","BEBAN_UMUM",""],
  ["7016","Biaya Pajak PPH 21","DR","Y","BEBAN_UMUM",""],
  ["7017","Biaya Pajak PPH 23","DR","N","BEBAN_UMUM","Y"],
  ["7018","Biaya Pajak PPH Pasal 4 (ayat 2)","DR","N","BEBAN_UMUM","Y"],
  ["7019","Biaya Pajak PPH Pasal 25/29","DR","Y","BEBAN_PAJAK",""],
  ["7020","Biaya Pajak Lainnya","DR","Y","BEBAN_UMUM",""],
  ["7021","Biaya Koordinasi","DR","Y","BEBAN_UMUM",""],
  ["7022","Biaya Service Kendaraan","DR","Y","BEBAN_UMUM",""],
  ["7023","Biaya Rumah Tangga","DR","Y","BEBAN_UMUM",""],
  ["7024","Biaya Transportasi","DR","N","BEBAN_UMUM",""],
  ["7025","Biaya Utilitas (Listrik, Air, Telp, Internet & Iuran Keamanan)","DR","N","BEBAN_UMUM",""],
  ["7026","Biaya Kesehatan (Obat-obatan)","DR","Y","BEBAN_UMUM",""],
  ["7027","Biaya ATK","DR","N","BEBAN_UMUM",""],
  ["7028","Biaya Kirim","DR","N","BEBAN_UMUM",""],
  ["7029","Biaya Perijinan","DR","Y","BEBAN_UMUM",""],
  ["7030","Biaya Jasa Konsultan","DR","N","BEBAN_UMUM",""],
  ["7031","Biaya Perjalanan Dinas","DR","N","BEBAN_UMUM",""],
  ["7032","Biaya Entertaint","DR","N","BEBAN_UMUM",""],
  ["7033","Biaya Dinas BOC BOD","DR","Y","BEBAN_UMUM",""],
  ["7034","Biaya Donasi/Sumbangan","DR","Y","BEBAN_UMUM","Y"],
  ["7035","Biaya Sample","DR","Y","BEBAN_UMUM",""],
  ["7036","Biaya Percetakan","DR","Y","BEBAN_UMUM",""],
  ["7037","Biaya Pembulatan","DR","Y","BEBAN_UMUM",""],
  ["7038","Biaya Penyusutan","DR","Y","BEBAN_PENYUSUTAN",""],
  ["7039","Biaya Spare Parts Mesin/Peralatan Workshop","DR","Y","BEBAN_UMUM",""],
  ["7040","Biaya Perbaikan dan Pemeliharaan Mesin","DR","Y","BEBAN_UMUM",""],
  ["7041","Biaya Perbaikan dan Pemeliharaan Peralatan","DR","Y","BEBAN_UMUM",""],
  ["7042","Biaya Amortisasi","DR","Y","BEBAN_PENYUSUTAN",""],
  ["7099","Biaya Operasional","DR","Y","BEBAN_UMUM",""],
  ["8001","Pendapatan Bunga Bank","CR","Y","PENDAPATAN_LAIN","Y"],
  ["8002","Selisih Kurs Laba  Belum Terealisasi","CR","Y","PENDAPATAN_LAIN",""],
  ["8003","Pendapatan lain-lain","CR","Y","PENDAPATAN_LAIN",""],
  ["8101","Biaya Admin Bank","DR","Y","BEBAN_LAIN",""],
  ["8102","Biaya Pajak Pendapatan Bunga","DR","Y","BEBAN_LAIN","Y"],
  ["8103","Biaya Bunga Pinjaman","DR","Y","BEBAN_BUNGA",""],
  ["8104","Biaya Penyisihan piutang","DR","Y","BEBAN_LAIN",""],
  ["8105","Biaya Bunga Leasing","DR","Y","BEBAN_BUNGA",""],
  ["8106","Biaya Pinjaman","DR","Y","BEBAN_BUNGA",""],
  ["8500","Provisi Pajak Penghasilan Badan","DR","Y","BEBAN_PAJAK",""],
  ["8600","Manfaat Pajak Tangguhan","CR","Y","PAJAK_TANGGUHAN",""],
  ["8601","Biaya Pajak Tangguhan","DR","Y","PAJAK_TANGGUHAN",""]
];
